disqus:
  enable: true
  shortname: counter2015

google_search: true
google_analytics: G-N73FWWZR9G
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
fancybox: true ## If you want to use fancybox please set the value to true.
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: false ## If you want to add list number to toc please set the value to true.
shareto: true ## If you want to use the share button please set the value to true, and you must have hexo-helper-qrcode installed.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
wordcount: true ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

post_copyright:
  enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: counter2015 ## Your author name, e.g. tufu9441
  copyright_text: <p>除另有声明外，本博客文章均采用 <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/cn/"><b>知识共享(Creative Commons) 署名-非商业性使用-相同方式共享 3.0 中国大陆许可协议</b></a> 进行许可。</p>

mathjax: true

cplantuml: ## Using PlantUML to generate UML diagram, must install hexo-filter-plantuml (https://github.com/miao1007/hexo-filter-plantuml).
  render: "PlantUMLServer" ## Local or PlantUMLServer.
  outputFormat: "svg" ## Common options: svg/png
copycode: true ## If you want to enable one-click copy of the code blocks, set the value to true.
dark: false ## If you want to toggle between light/dark themes, set the value to true.
totop: true ## If you want to use the rocketship button to return to the top, set the value to true.
external_css: false ## If you want to load an external CSS file, set the value to true and create a file named "external.css" in the source/css folder.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, recent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: hushhw's blog 身经百战见得多了
    url: https://wiki.hushhw.cn
  - title: isekiのNote
    url: https://blog.iseki.space
  - title: Razetory的技术博客
    url: https://razertory.github.io
  - title: ajin的博客
    url: https://blog.ajin.cloud

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Static files
js: js
css: css

# warning
warning:
  days: 100
  text: '本文发表的时间过于久远，其中的信息可能已经有所发展或者不再适用于现阶段'

# Theme version
version: 1.0.0
